/* 
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Other/SQLTemplate.sql to edit this template
 */
/**
 * Author:  Fernando A
 * Created: 17 ene 2025
 */

--------------------------------------------------------
-- Archivo creado  - viernes-enero-17-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ESTADO
--------------------------------------------------------

  CREATE TABLE "DAM2JP"."ESTADO" 
   (	"TIPOESTADO" VARCHAR2(2 BYTE), 
	"NOMBREESTADO" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LLAMADAS
--------------------------------------------------------

  CREATE TABLE "DAM2JP"."LLAMADAS" 
   (	"NUMEROTELF" NUMBER, 
	"FECHAHORA" DATE, 
	"UBICACION" VARCHAR2(255 BYTE), 
	"ESTADO" VARCHAR2(2 BYTE), 
	"DESCRIPCION" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MOVILIZACIONES
--------------------------------------------------------

  CREATE TABLE "DAM2JP"."MOVILIZACIONES" 
   (	"IDMOVILIZACION" NUMBER, 
	"NUMEROTELF" NUMBER, 
	"NUMEROUNIDAD" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TIPOUNIDAD
--------------------------------------------------------

  CREATE TABLE "DAM2JP"."TIPOUNIDAD" 
   (	"TIPOUNIDAD" VARCHAR2(2 BYTE), 
	"NOMBREUNIDAD" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table UNIDADES
--------------------------------------------------------

  CREATE TABLE "DAM2JP"."UNIDADES" 
   (	"NUMEROUNIDAD" NUMBER, 
	"TIPOUNIDAD" VARCHAR2(2 BYTE), 
	"DISPONIBILIDAD" BOOLEAN
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into DAM2JP.ESTADO
SET DEFINE OFF;
Insert into DAM2JP.ESTADO (TIPOESTADO,NOMBREESTADO) values ('DE','Denegado');
Insert into DAM2JP.ESTADO (TIPOESTADO,NOMBREESTADO) values ('AT','Atendida');
Insert into DAM2JP.ESTADO (TIPOESTADO,NOMBREESTADO) values ('NT','Sin atender');
Insert into DAM2JP.ESTADO (TIPOESTADO,NOMBREESTADO) values ('PC','En proceso');
REM INSERTING into DAM2JP.LLAMADAS
SET DEFINE OFF;
Insert into DAM2JP.LLAMADAS (NUMEROTELF,FECHAHORA,UBICACION,ESTADO,DESCRIPCION) values ('123456789',to_date('01/10/23','DD/MM/RR'),'Centro','AT','Llamada de emergencia');
Insert into DAM2JP.LLAMADAS (NUMEROTELF,FECHAHORA,UBICACION,ESTADO,DESCRIPCION) values ('987654321',to_date('01/10/23','DD/MM/RR'),'Norte','NT','Consulta de información');
Insert into DAM2JP.LLAMADAS (NUMEROTELF,FECHAHORA,UBICACION,ESTADO,DESCRIPCION) values ('456789123',to_date('01/10/23','DD/MM/RR'),'Sur','PC','Llamada pendiente de confirmación');
REM INSERTING into DAM2JP.MOVILIZACIONES
SET DEFINE OFF;
REM INSERTING into DAM2JP.TIPOUNIDAD
SET DEFINE OFF;
Insert into DAM2JP.TIPOUNIDAD (TIPOUNIDAD,NOMBREUNIDAD) values ('AM','Ambulancia');
Insert into DAM2JP.TIPOUNIDAD (TIPOUNIDAD,NOMBREUNIDAD) values ('BM','Bombero');
Insert into DAM2JP.TIPOUNIDAD (TIPOUNIDAD,NOMBREUNIDAD) values ('PN','Policia Nacional');
REM INSERTING into DAM2JP.UNIDADES
SET DEFINE OFF;
Insert into DAM2JP.UNIDADES (NUMEROUNIDAD,TIPOUNIDAD,DISPONIBILIDAD) values ('1','AM','true');
Insert into DAM2JP.UNIDADES (NUMEROUNIDAD,TIPOUNIDAD,DISPONIBILIDAD) values ('2','BM','false');
Insert into DAM2JP.UNIDADES (NUMEROUNIDAD,TIPOUNIDAD,DISPONIBILIDAD) values ('3','PN','true');
--------------------------------------------------------
--  DDL for Index SYS_C008706
--------------------------------------------------------

  CREATE UNIQUE INDEX "DAM2JP"."SYS_C008706" ON "DAM2JP"."ESTADO" ("TIPOESTADO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008708
--------------------------------------------------------

  CREATE UNIQUE INDEX "DAM2JP"."SYS_C008708" ON "DAM2JP"."TIPOUNIDAD" ("TIPOUNIDAD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008712
--------------------------------------------------------

  CREATE UNIQUE INDEX "DAM2JP"."SYS_C008712" ON "DAM2JP"."LLAMADAS" ("NUMEROTELF") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008715
--------------------------------------------------------

  CREATE UNIQUE INDEX "DAM2JP"."SYS_C008715" ON "DAM2JP"."UNIDADES" ("NUMEROUNIDAD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008719
--------------------------------------------------------

  CREATE UNIQUE INDEX "DAM2JP"."SYS_C008719" ON "DAM2JP"."MOVILIZACIONES" ("IDMOVILIZACION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008706
--------------------------------------------------------

  CREATE UNIQUE INDEX "DAM2JP"."SYS_C008706" ON "DAM2JP"."ESTADO" ("TIPOESTADO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008712
--------------------------------------------------------

  CREATE UNIQUE INDEX "DAM2JP"."SYS_C008712" ON "DAM2JP"."LLAMADAS" ("NUMEROTELF") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008719
--------------------------------------------------------

  CREATE UNIQUE INDEX "DAM2JP"."SYS_C008719" ON "DAM2JP"."MOVILIZACIONES" ("IDMOVILIZACION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008708
--------------------------------------------------------

  CREATE UNIQUE INDEX "DAM2JP"."SYS_C008708" ON "DAM2JP"."TIPOUNIDAD" ("TIPOUNIDAD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008715
--------------------------------------------------------

  CREATE UNIQUE INDEX "DAM2JP"."SYS_C008715" ON "DAM2JP"."UNIDADES" ("NUMEROUNIDAD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ESTADO
--------------------------------------------------------

  ALTER TABLE "DAM2JP"."ESTADO" MODIFY ("NOMBREESTADO" NOT NULL ENABLE);
  ALTER TABLE "DAM2JP"."ESTADO" ADD PRIMARY KEY ("TIPOESTADO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LLAMADAS
--------------------------------------------------------

  ALTER TABLE "DAM2JP"."LLAMADAS" MODIFY ("FECHAHORA" NOT NULL ENABLE);
  ALTER TABLE "DAM2JP"."LLAMADAS" MODIFY ("UBICACION" NOT NULL ENABLE);
  ALTER TABLE "DAM2JP"."LLAMADAS" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "DAM2JP"."LLAMADAS" ADD PRIMARY KEY ("NUMEROTELF")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DAM2JP"."LLAMADAS" ADD CONSTRAINT "CHK_NUMERO_TELEFONO" CHECK (LENGTH(NUMEROTELF) >= 9) ENABLE;
--------------------------------------------------------
--  Constraints for Table MOVILIZACIONES
--------------------------------------------------------

  ALTER TABLE "DAM2JP"."MOVILIZACIONES" MODIFY ("NUMEROTELF" NOT NULL ENABLE);
  ALTER TABLE "DAM2JP"."MOVILIZACIONES" MODIFY ("NUMEROUNIDAD" NOT NULL ENABLE);
  ALTER TABLE "DAM2JP"."MOVILIZACIONES" ADD PRIMARY KEY ("IDMOVILIZACION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TIPOUNIDAD
--------------------------------------------------------

  ALTER TABLE "DAM2JP"."TIPOUNIDAD" MODIFY ("NOMBREUNIDAD" NOT NULL ENABLE);
  ALTER TABLE "DAM2JP"."TIPOUNIDAD" ADD PRIMARY KEY ("TIPOUNIDAD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table UNIDADES
--------------------------------------------------------

  ALTER TABLE "DAM2JP"."UNIDADES" MODIFY ("TIPOUNIDAD" NOT NULL ENABLE);
  ALTER TABLE "DAM2JP"."UNIDADES" ADD PRIMARY KEY ("NUMEROUNIDAD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DAM2JP"."UNIDADES" MODIFY ("DISPONIBILIDAD" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table LLAMADAS
--------------------------------------------------------

  ALTER TABLE "DAM2JP"."LLAMADAS" ADD FOREIGN KEY ("ESTADO")
	  REFERENCES "DAM2JP"."ESTADO" ("TIPOESTADO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MOVILIZACIONES
--------------------------------------------------------

  ALTER TABLE "DAM2JP"."MOVILIZACIONES" ADD FOREIGN KEY ("NUMEROTELF")
	  REFERENCES "DAM2JP"."LLAMADAS" ("NUMEROTELF") ENABLE;
  ALTER TABLE "DAM2JP"."MOVILIZACIONES" ADD FOREIGN KEY ("NUMEROUNIDAD")
	  REFERENCES "DAM2JP"."UNIDADES" ("NUMEROUNIDAD") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table UNIDADES
--------------------------------------------------------

  ALTER TABLE "DAM2JP"."UNIDADES" ADD FOREIGN KEY ("TIPOUNIDAD")
	  REFERENCES "DAM2JP"."TIPOUNIDAD" ("TIPOUNIDAD") ENABLE;
